[metrics]
# Exposes Prometheus metrics
go_process = true

# API server
[service]
# Host and port
address = ":5000"

# Geth API endpoints
[chain]
graphql_endpoint = ""
ws_endpoint      = ""
rpc_endpoint     = ""
testnet          = true
registry_address = ""

# Syncer configs
[syncer]
# Maximum number of missing blocks pushed into the worker queue every janitor sweep
janitor_queue_size     = 250
# Number of goroutines assigned to the worker pool
janitor_concurrency    = 3
# Syncer start block
initial_lower_bound    = ""
# Janitor sweep interval, should take into account concurrency and queue_size
janitor_sweep_interval = 10

[postgres]
dsn   = ""

# https://docs.nats.io/
[jetstream]
endpoint               = ""
# Duration JetStream should keep the message before GC
persist_duration_hrs = 48
# Duration to ignore duplicate transactions (e.g. due to restart)
dedup_duration_hrs   = 6
