[metrics]
# Exposes Prometheus metrics
go_process = true

# API server
[api]
# Host and port
address = ":8085"

# Geth API endpoints
[chain]
graphql_endpoint = "https://rpc.alfajores.celo.grassecon.net/graphql"
ws_endpoint      = "wss://ws.alfajores.celo.grassecon.net"

# Syncer configs
[syncer]
# Maximum number of missing blocks pushed into the worker queue every janitor sweep
janitor_queue_size     = 500
# Number of goroutines assigned to the worker pool
janitor_concurrency    = 5
# Syncer start block
initial_lower_bound    = 16373156
# Janitor sweep interval, should take into account concurrency and queue_size
janitor_sweep_interval = 5

[postgres]
dsn   = "postgres://postgres:postgres@localhost:5432/cic_chain_events"

# https://docs.nats.io/
[jetstream]
endpoint               = "nats://localhost:4222"
# Duration JetStream should keep the message before GC
persist_duration_hours = 48
# Duration to ignore duplicate transactions (e.g. due to restart)
dedup_duration_hours   = 6
