[metrics]
go_process = true

[api]
address = ":8080"

[chain]
graphql_endpoint = "https://rpc.celo.grassecon.net/graphql"
ws_endpoint      = "wss://ws.celo.grassecon.net"

[indexer]
batch_size          = 200
concurrency         = 3
head_block_lag      = 5
idle_worker_timeout = 1
initial_lower_bound = 17034445
queue_size          = 1250
sweep_interval      = 10

[postgres]
dsn   = "postgres://postgres:postgres@localhost:5432/cic_chain_events"