version: '3.9'
services:     
  postgres:
    image: postgres:14-alpine
    restart: unless-stopped
    user: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cic_chain_events
    volumes:
      - cic-indexer-pg:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  nats:
    image: nats:2.9
    restart: unless-stopped
    command: "-js -sd /nats/data"
    volumes:
      - cic-indexer-nats:/nats/data
    ports:
      - '4222:4222'
      - '8222:8222'
volumes:
  cic-indexer-pg:
    driver: local
  cic-indexer-nats:
    driver: local    