version: '3.9'
services:   
  postgres:
    image: postgres:14-alpine
    restart: unless-stopped
    user: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cic_chain_events
    volumes:
      - cic-indexer-pg:/var/lib/postgresql/data
    ports:  
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  nats:
    image: nats:2.9
    restart: unless-stopped
    command: "-js -sd /nats/data"
    volumes:
      - cic-indexer-nats:/nats/data
    ports:
      - '4222:4222'
      - '8222:8222'
  cic-chain-events:
    image: ghcr.io/inethi/inethi-cic-chain-events/cic-chain-events:v0.1.0
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      nats:
        condition: service_started
    env_file:
      - events.env
  benthos:
    image: jeffail/benthos:4
    restart: unless-stopped
    depends_on:
      nats:
        condition: service_started
    volumes:
      - ./benthos.yaml:/benthos.yaml      
volumes:
  cic-indexer-pg:
    driver: local
  cic-indexer-nats:
    driver: local    